FROM alpine:3.20

# Cliente MySQL + zona horaria
RUN apk add --no-cache mysql-client bash tzdata

ENV TZ=Atlantic/Canary

# Script de backup
COPY backup.sh /usr/local/bin/backup.sh
RUN chmod +x /usr/local/bin/backup.sh
